spring:
  profiles:
    include:
      - secret
  output:
    ansi:
      enabled: always
  jpa:
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: kream
        show_sql: true
        format_sql: true
        use_sql_comments: true
  jackson:
    property-naming-strategy: SNAKE_CASE
logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error