spring:
    devtools:
        livereload:
            enabled: true
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ENC(Y163CTUnIqK2deK/SBNbmRO3EOlFmmf21bqEsBMUIhAaKeOfN74rZ6rTH8hEu4C+Y/iGiHR7JNNkKCPdEprYQQ==)
        username: ENC(vjN4t4sGv6WKsNu+rWO/y3xB3cV9vg8+)
        password: ENC(iGYbYIj/tmfZShAopYp8qnP9Tl21tqI2)
        hikari:
            auto-commit: false
            connection-test-query: SELECT 1
            minimum-idle: 10
            maximum-pool-size: 50
    jpa:
        generate-ddl: false
        open-in-view: false
        show-sql: true
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                use_sql_comments: true

cloud:
   aws:
       s3:
           bucket: ENC(dXzoDfTMqaBLOi0HPXWyT2l2kslSN8ME)
       region:
           static: ap-northeast-2
       stack:
           auto: false
       credentials:
           accessKey: ENC(z5Cmrlnpa3wQ3+zqAFxbGm2h+XYD76hwlK4I92w51Do=)
           secretKey: ENC(Q4duQxpbmUXRLjsp+f13ZDJSDsb7Uq4mBozFW0E8oEyf2HdW13EJKJup/mDpZMQY+//nvHAK17Y=)

logging:
    level:
        com:
            amazonaws:
                util:
                    EC2MetadataUtils: error
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
