name: Build kreamzone application

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          printf ${{ secrets.SECRET_PROPERTIES }} >> src/main/java/com/ehago/kreamzone/resource/application-secret.yml
          ./gradlew build
