name: Deploy kreamzone application
on:
  push:
    branches: [ develop ]

env:
  FULL_IMAGE_NAME: ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build image and push to docker hub
        run: |
          ./gradlew build --exclude-task test
          docker build -t ${{ env.FULL_IMAGE_NAME }} .
          docker login \
            --username ${{ secrets.DOCKER_USER }} \
            --password ${{ secrets.DOCKER_USER_PASSWORD }}
          docker push ${{ env.FULL_IMAGE_NAME }}
      - name: Connect to server and restart container
        if: ${{ success() }}
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            export ENCRYPTOR_PASSWORD=${{ secrets.ENCRYPTOR_PASSWORD }}
            docker pull ${{ env.FULL_IMAGE_NAME }}
            docker stop ${{ secrets.IMAGE_NAME }}
            docker rm ${{ secrets.IMAGE_NAME }}
            docker run \
              -d --name ${{ secrets.IMAGE_NAME }} \
              -p 80:8080 \
              -v /var/log/${{ secrets.IMAGE_NAME }}:/tmp/log/${{ secrets.IMAGE_NAME }} \
              -e ENCRYPTOR_PASSWORD=${{ secrets.ENCRYPTOR_PASSWORD }} \
              ${{ env.FULL_IMAGE_NAME }}
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
