name: Deploy kreamzone application
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build image and push to docker hub
        run: |
          ./gradlew build --exclude-task test
          docker build -t ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }} .
          docker login --username ${{ secrets.DOCKER_USER }} --password ${{ secrets.DOCKER_USER_PASSWORD }}
          docker push ${{ secrets.REGISTRY }}/${{ secrets.IMAGE_NAME }}
      - name: Remote SSH Commands
        if: ${{ success() }}
        uses: fifsky/ssh-action@v0.0.5
        with:
          command: |
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker stop ${{ secrets.APP_NAME }}
            docker rm ${{ secrets.APP_NAME }}
            docker run -d --name ${{ secrets.APP_NAME }} -p 80:8080 -e ENCRYPTOR_PASSWORD=${{ secrets.ENCRYPTOR_PASSWORD }} ${{ secrets.DOCKER_IMAGE_NAME }}
          host: ${{ secrets.SERVER_IP }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
